```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(umap)
library(scales)

# Load data
data <- read_csv("/Users/henrysun_1/Desktop/Duke/2024-2025/Summer 2024/fishics/data/data_for_henry_2024.csv")
fish_asvs <- data %>%
  select(12:ncol(data))

fish_asvs_scaled <- scale(fish_asvs)

# Perform UMAP
umap_result <- umap(fish_asvs_scaled, n_neighbors = 10, min_dist = 0.1, n_components = 2, random_state = 42)

# Create a new data frame with UMAP results
umap_df <- data.frame(UMAP1 = umap_result$layout[, 1], UMAP2 = umap_result$layout[, 2])
data <- data %>%
  mutate(UMAP1 = umap_result$layout[, 1],
         UMAP2 = umap_result$layout[, 2])
# Save the UMAP results to a CSV file
write_csv(umap_df, "/Users/henrysun_1/Desktop/Duke/2024-2025/Summer 2024/fishics/data/umap_latent_space.csv")
# print(head(umap_df))

```


```{r}
# Plot UMAP results colored by date
ggplot(data, aes(x = UMAP1, y = UMAP2, color = date)) +
  geom_point(size = 3) +
  scale_color_manual(values = hue_pal()(length(unique(data$date)))) +
  theme_minimal() +
  ggtitle("UMAP of Fish ASVs colored by date") +
  xlab("UMAP Component 1") +
  ylab("UMAP Component 2") +
  theme(legend.position = "right")

```
